### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by BootNeos** [Sensirion/raspberry-pi-i2c-scd4x#4]
I am totally confused about the 'pull-up-resistor-topic'.
Your image shows, that it is possible to connect the SCD41 directly to the I2C-Pins of the Raspberry Pi. 
This leads to my question: Is it right, that no extra pull-up resistors are needed? (Except the 1.8k ones in the raspberry pi)
Therefore, 1.8k is enough? (In the datasheet, 10k is suggested)

Many thanks in advance.

**Comment by MBjoern** [comment]
Hi BootNeos

The Raspberry Pi should have internal pull-up resistors taking care of this point. In my experience, hooking up the SCD41 directly to the i2c pins as depicted in this repository works very well.

I hope that helps
Best regards
Björn

**Comment by BootNeos** [comment]
Okay, thanks! :)

Best regards

**Comment by rnestler** [comment]
Just for clarification in case anybody lands at this issue:

> Therefore, 1.8k is enough? (In the datasheet, 10k is suggested)

1.8kΩ is a lower resistance than the 10kΩ from the datasheet, so the pull (and thus current consumption) is stronger. See also https://www.i2c-bus.org/i2c-primer/how-i2c-hardware-works/
