### ISSUE TITLE
functions not working 

### ISSUE THREAD

**Issue by avathompson30** [Sensirion/raspberry-pi-i2c-scd4x#9]
I downloaded this git hub file to my raspberry pi. The code recognizes the header files I am including but does not recognize certain functions within the files. I keep getting a message that the function is an undefined reference. When I complied the driver it was successful, and some of the functions it understands but not others. Also I am using Geany as my IDE and coding in C. Please help thank you! Also the scd4x_i2c_example_usage.c runs in the terminal not in Geany. None of the files with .c run on the platform only .h

**Comment by qfisch** [comment]
Hello @avathompson30 

Did you follow the steps in the [setup guide](https://github.com/Sensirion/raspberry-pi-i2c-scd4x?tab=readme-ov-file#setup-guide) (README) ? 
If you did, at which step do you see an error ?

Quentin

**Comment by avathompson30** [comment]
Yes I followed those steps. I was able to fix my problem. I am new to the
Raspberry Pi and did not know I had to change the build commands. I made
those changes and now I am able to utilize the functions from the files.
Thank you for getting back to me.

**Comment by qfisch** [comment]
Great to hear you manage to solve your problem.

Cheers
Q
